import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#f3faff",
        "surface-dim": "#cfdce3",
        "surface-variant": "#d9e4ea",
        "on-surface": "#2a3439",
        "secondary-fixed": "#c9e7f7",
        "on-primary-fixed-variant": "#0058bb",
        "error-dim": "#4e0309",
        "on-secondary-fixed-variant": "#435f6d",
        "surface-bright": "#f7f9fb",
        "outline": "#717c82",
        "inverse-primary": "#4b8eff",
        "secondary-fixed-dim": "#bbd9e9",
        "on-tertiary-fixed-variant": "#54516d",
        "on-primary-fixed": "#003d85",
        "background": "#f7f9fb",
        "secondary-container": "#c9e7f7",
        "on-background": "#2a3439",
        "on-tertiary": "#fcf7ff",
        "on-error-container": "#752121",
        "surface-container-high": "#e1e9ee",
        "on-primary-container": "#004ea8",
        "on-primary": "#f7f7ff",
        "inverse-surface": "#0b0f10",
        "surface-container-low": "#f0f4f7",
        "surface": "#f7f9fb",
        "on-error": "#fff7f6",
        "on-secondary-container": "#395663",
        "surface-container": "#e8eff3",
        "tertiary-fixed-dim": "#cac6e6",
        "on-secondary-fixed": "#264350",
        "tertiary-fixed": "#d8d3f4",
        "primary-container": "#d8e2ff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#c2d4ff",
        "on-surface-variant": "#566166",
        "tertiary-dim": "#53506b",
        "outline-variant": "#a9b4b9",
        "inverse-on-surface": "#9a9d9f",
        "on-tertiary-fixed": "#37354f",
        "primary": "#005bc1",
        "primary-dim": "#004faa",
        "secondary": "#466370",
        "surface-tint": "#005bc1",
        "tertiary": "#5f5c78",
        "tertiary-container": "#d8d3f4",
        "secondary-dim": "#3a5764",
        "error": "#9f403d",
        "error-container": "#fe8983",
        "on-tertiary-container": "#4a4863",
        "surface-container-highest": "#d9e4ea",
        "success": "#10b981", 
      },
      fontFamily: {
        "headline": ["var(--font-manrope)", "sans-serif"],
        "body": ["var(--font-inter)", "sans-serif"],
        "label": ["var(--font-inter)", "sans-serif"]
      },
    },
  },
  plugins: [],
};
export default config;
