version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: proclinic-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: proclinic
      POSTGRES_PASSWORD: proclinic123
      POSTGRES_DB: proclinic
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U proclinic"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: proclinic-api
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proclinic-web
    ports:
      - "5173:80"
    depends_on:
      - api
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: proclinic_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
      TZ: America/Sao_Paulo
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  db_data:



